### ISSUE TITLE
test_antipodal_grasp_sampler failing

### ISSUE THREAD

**Issue by manuelli** [BerkeleyAutomation/dex-net#12]
I managed to install `dexnet` and all dependencies successfully. However when running `python setup.py test` the  `test_antipodal_grasp_sampler` test is failing (along with several others). They are all failing for the same reason, a rotation matrix not having determinant 1. The error is

```
======================================================================
ERROR: test_antipodal_grasp_sampler (test.grasping_test.GraspTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/manuelli/spartan_grasp/catkin_ws/src/dex-net/test/grasping_test.py", line 215, in test_antipodal_grasp_sampler
    sdf = sf.read()
  File "/home/manuelli/meshpy/meshpy/sdf_file.py", line 62, in read
    return self._read_3d()
  File "/home/manuelli/meshpy/meshpy/sdf_file.py", line 95, in _read_3d
    return sdf.Sdf3D(sdf_data, origin, resolution)
  File "/home/manuelli/meshpy/meshpy/sdf.py", line 245, in __init__
    self.T_sdf_grid_ = self.T_grid_sdf_.inverse()
  File "/home/manuelli/spartan_grasp/catkin_ws/src/autolab_core/autolab_core/rigid_transformations.py", line 1100, in inverse
    to_frame=self._from_frame)
  File "/home/manuelli/spartan_grasp/catkin_ws/src/autolab_core/autolab_core/rigid_transformations.py", line 980, in __init__
    RigidTransform.__init__(self, rotation, translation, from_frame, to_frame)
  File "/home/manuelli/spartan_grasp/catkin_ws/src/autolab_core/autolab_core/rigid_transformations.py", line 75, in __init__
    self.rotation = rotation
  File "/home/manuelli/spartan_grasp/catkin_ws/src/autolab_core/autolab_core/rigid_transformations.py", line 131, in rotation
    self._check_valid_rotation(rotation)
  File "/home/manuelli/spartan_grasp/catkin_ws/src/autolab_core/autolab_core/rigid_transformations.py", line 100, in _check_valid_rotation
    raise ValueError('Illegal rotation. Must have determinant == 1.0')
ValueError: Illegal rotation. Must have determinant == 1.0

======================================================================

```

I traced the code path and it seems like the error is arising from [here](https://github.com/BerkeleyAutomation/meshpy/blob/master/meshpy/sdf.py#L238). I'm not sure how this can be happening since the default argument for the rotation matrix is `rotation=np.eye(3)`, and since the arg isn't being passed that's what should be happening here, and the identity definitely has a determinant of 1.

**Comment by jeffmahler** [comment]
One of the students on the project committed a bug to autolab_core. The master branch on autolab_core is up-to-date, so if you install autolab_core from source then it should be ok (and if you already did that, then pull fresh from master). We will update the autolab_core PyPi package ASAP.

**Comment by manuelli** [comment]
Ok that fixed it. I was on master as of 3 days ago but I just pulled down the bug fix. All tests are passing now. Also FYI if you are looking for a solid transformations library for Python I really like the vtkPython with vtkTransform.

**Comment by jeffmahler** [comment]
Cool thanks for the tip, I'll check that out. The autolab_core stuff is a port of an old library called tfx from one of our past grads.

**Comment by manuelli** [comment]
We use the vtkTransform class heavily in our `director` visualizer. Here is a little wrapper utility class that shows some API usage https://github.com/RobotLocomotion/director/blob/master/src/python/director/transformUtils.py
