### ISSUE TITLE
Floating point exception core dumped

### ISSUE THREAD

**Issue by kundan09** [BerkeleyAutomation/dex-net#23]
@jeffmahler 

I executed code to test dexnet installtion on ubuntu 14 and 16 both in CPU machine.

user/catkin_ws/src/dexnet python setup.py test .

**floating point exception core dumped.** error i got .
robo@dex:~/catkin_ws/src/dex-net$ python setup.py test
running test
running egg_info
writing requirements to src/dex_net.egg-info/requires.txt
writing src/dex_net.egg-info/PKG-INFO
writing top-level names to src/dex_net.egg-info/top_level.txt
writing dependency_links to src/dex_net.egg-info/dependency_links.txt
reading manifest file 'src/dex_net.egg-info/SOURCES.txt'
writing manifest file 'src/dex_net.egg-info/SOURCES.txt'
running build_ext
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Failed to import ROS in Kinect2_sensor.py. Kinect will not be able to be used in bridged mode
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
test_antipodal_grasp_sampler (test.grasping_test.GraspTest) ... ERROR:root:Singular matrix. Probably a bug
ERROR:root:Singular matrix. Probably a bug
ERROR:root:Singular matrix. Probably a bug
ok
test_contacts (test.grasping_test.GraspTest) ... ok
test_find_contacts (test.grasping_test.GraspTest) ... ok
test_force_closure (test.grasping_test.GraspTest) ... ok
test_grasp_quality_functions (test.grasping_test.GraspTest) ... /home/robo/catkin_ws/src/dex-net/src/dexnet/grasping/grasp.py:222: RuntimeWarning: invalid value encountered in arccos
  axis_dist = (2.0 / np.pi) * np.arccos(np.abs(g1.axis.dot(g2.axis)))
ok
test_init_grasp (test.grasping_test.GraspTest) ... ok
test_init_graspable (test.grasping_test.GraspTest) ... ok
test_init_gripper (test.grasping_test.GraspTest) ... ok
test_min_norm_vector_in_facet (test.grasping_test.GraspTest) ... ok
test_wrench_in_positive_span (test.grasping_test.GraspTest) ... ok
test_gaussian_uniform_alloc (test.learning_test.LearningTest) ... ok
test_thompson_sampling (test.learning_test.LearningTest) ... ok
test_uniform_alloc (test.learning_test.LearningTest) ... ok
test_illegal_create (test.database_test.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest) ... Input mesh  /home/robo/catkin_ws/src/dex-net/data/test/models/bar_clamp.obj
output mesh  /home/robo/catkin_ws/src/dex-net/.dexnet/bar_clamp_proc.obj
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh bar_clamp.obj loaded has 1428 vn 476 fn
No Script to apply.
Mesh /home/robo/catkin_ws/src/dex-net/data/test/models/bar_clamp.obj saved as /home/robo/catkin_ws/src/dex-net/.dexnet/bar_clamp_proc.obj (1428 vn 476 fn)
Reading data.
Warning: 9 lines were ignored since they did not contain faces or vertices.
Read in 1428 vertices and 476 faces.
Resolution: 0.000716689 with real dimension 0.064502
Center of grid 0 0 0
Bound box size: (-0.0358344 -0.0358344 -0.0358344) to (0.021729 0.02 0.032251) with dimensions 100 100 100.
Computing signed distance field.
Writing results to: .dexnet/bar_clamp_proc.sdf
Processing complete.
chmod: changing permissions of '.dexnet/bar_clamp_proc.sdf': Operation not permitted
ERROR

======================================================================
ERROR: test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robo/catkin_ws/src/dex-net/test/database_test.py", line 168, in test_new_database_and_graspable
    stable_pose)
  File "/usr/local/lib/python2.7/dist-packages/meshpy/mesh_renderer.py", line 716, in wrapped_images_viewsphere
    return self.wrapped_images(mesh, vs_disc.object_to_camera_poses(), render_mode, stable_pose=stable_pose, mat_props=mat_props, light_props=light_props)
  File "/usr/local/lib/python2.7/dist-packages/meshpy/mesh_renderer.py", line 587, in wrapped_images
    debug=debug)
  File "/usr/local/lib/python2.7/dist-packages/meshpy/mesh_renderer.py", line 489, in images
    c, d = meshrender.render_mesh([P],
AttributeError: 'module' object has no attribute 'render_mesh'

----------------------------------------------------------------------
Ran 15 tests in 146.936s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
**Floating point exception (core dumped)**

**Comment by maxixb** [comment]
I have the exact same issue...

**Comment by Maultaschenboii** [comment]
I have exactly the same problem.

**Comment by jeffmahler** [comment]
I suspect the meshrender binary didn't install properly. Let's see if you can find the binary

Open a Python terminal and find the location of meshpy
```
python
>>> import meshpy
>>> print meshpy.__file__
``` 
Then look for the file `meshrender.so` in the directory that is printed from the above statements.

If you do not find it, then your build failed. Change directories to `/path/to/meshpy/clone` and run the commands in this file from [the command line](https://github.com/BerkeleyAutomation/meshpy/blob/master/install_meshrender.sh). Paste any errors here.

**Comment by maxixb** [comment]
At first thank you for fast reply.
You are right, the problem ist meshrender.so file, it dosn´t exist. 
I tried to run the comands like you sad, but i get instant an error if i run cmake ...

Output in the command line:
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Found PythonLibs: /usr/lib/i386-linux-gnu/libpython2.7.so (found suitable version "2.7.6", minimum required is "2.7") 
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/i386-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/i386-linux-gnu/libGL.so  
-- Found GLUT: /usr/lib/i386-linux-gnu/libglut.so  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   python
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLUT_Xi_LIBRARY (ADVANCED)
    linked by target "meshrender" in directory /dex-net/deps/meshpy/meshpy
GLUT_Xmu_LIBRARY (ADVANCED)
    linked by target "meshrender" in directory /dex-net/deps/meshpy/meshpy

-- Configuring incomplete, errors occurred!
See also "/dex-net/deps/meshpy/build/CMakeFiles/CMakeOutput.log".

**Comment by jeffmahler** [comment]
Great, we are starting to make some progress. Looks like you are missing some necessary GL libraries.

[This link](https://ubuntuforums.org/showthread.php?t=1703770) suggests the following command:
```
sudo apt-get install libxmu-dev libxi-dev
```

@maxixb Can you run this command and try to compile again? Let me know if you have any errors.

**Comment by maxixb** [comment]
Great, it worked! Thank you!
But now I have trouble with the comand make...

I get this output...

/usr/bin/cmake -H/dex-net/deps/meshpy -B/dex-net/deps/meshpy/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /dex-net/deps/meshpy/build/CMakeFiles /dex-net/deps/meshpy/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Verzeichnis »/dex-net/deps/meshpy/build« wird betreten
make -f meshpy/CMakeFiles/meshrender.dir/build.make meshpy/CMakeFiles/meshrender.dir/depend
make[2]: Verzeichnis »/dex-net/deps/meshpy/build« wird betreten
cd /dex-net/deps/meshpy/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /dex-net/deps/meshpy /dex-net/deps/meshpy/meshpy /dex-net/deps/meshpy/build /dex-net/deps/meshpy/build/meshpy /dex-net/deps/meshpy/build/meshpy/CMakeFiles/meshrender.dir/DependInfo.cmake --color=
make[2]: Verzeichnis »/dex-net/deps/meshpy/build« wird verlassen
make -f meshpy/CMakeFiles/meshrender.dir/build.make meshpy/CMakeFiles/meshrender.dir/build
make[2]: Verzeichnis »/dex-net/deps/meshpy/build« wird betreten
/usr/bin/cmake -E cmake_progress_report /dex-net/deps/meshpy/build/CMakeFiles 1
[100%] Building CXX object meshpy/CMakeFiles/meshrender.dir/meshrender.cpp.o
cd /dex-net/deps/meshpy/build/meshpy && /usr/bin/c++   -Dmeshrender_EXPORTS -fPIC -I/usr/include/python2.7 -I/usr/include/i386-linux-gnu/python2.7    -o CMakeFiles/meshrender.dir/meshrender.cpp.o -c /dex-net/deps/meshpy/meshpy/meshrender.cpp
/dex-net/deps/meshpy/meshpy/meshrender.cpp: In function ‘boost::python::tuple render_mesh(boost::python::list, unsigned int, unsigned int, boost::python::numeric::array, boost::python::numeric::array, boost::python::numeric::array, boost::python::numeric::array, boost::python::numeric::array, bool, bool)’:
/dex-net/deps/meshpy/meshpy/meshrender.cpp:71:100: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool verts_readbuf_success = !PyObject_AsReadBuffer(verts.ptr(), &verts_raw_buffer, &verts_buflen);
                                                                                                    ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
/dex-net/deps/meshpy/meshpy/meshrender.cpp:72:96: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool tris_readbuf_success = !PyObject_AsReadBuffer(tris.ptr(), &tris_raw_buffer, &tris_buflen);
                                                                                                ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
/dex-net/deps/meshpy/meshpy/meshrender.cpp:73:100: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool norms_readbuf_success = !PyObject_AsReadBuffer(norms.ptr(), &norms_raw_buffer, &norms_buflen);
                                                                                                    ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
/dex-net/deps/meshpy/meshpy/meshrender.cpp:74:116: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool mat_props_readbuf_success = !PyObject_AsReadBuffer(mat_props.ptr(), &mat_props_raw_buffer, &mat_props_buflen);
                                                                                                                    ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
/dex-net/deps/meshpy/meshpy/meshrender.cpp:75:124: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool light_props_readbuf_success = !PyObject_AsReadBuffer(light_props.ptr(), &light_props_raw_buffer, &light_props_buflen);
                                                                                                                            ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
/dex-net/deps/meshpy/meshpy/meshrender.cpp:218:68: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
                                                        &proj_buflen);
                                                                    ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
/dex-net/deps/meshpy/meshpy/meshrender.cpp: In function ‘boost::python::list mul_array(boost::python::numeric::array, int)’:
/dex-net/deps/meshpy/meshpy/meshrender.cpp:365:71: error: invalid conversion from ‘long int*’ to ‘Py_ssize_t* {aka int*}’ [-fpermissive]
   bool isReadBuffer = !PyObject_AsReadBuffer(a.ptr(), &buffer, &bufLen);
                                                                       ^
In file included from /usr/include/python2.7/Python.h:133:0,
                 from /usr/include/boost/python/detail/wrap_python.hpp:142,
                 from /usr/include/boost/python/detail/prefix.hpp:13,
                 from /usr/include/boost/python/args.hpp:8,
                 from /usr/include/boost/python.hpp:11,
                 from /dex-net/deps/meshpy/meshpy/meshrender.cpp:1:
/usr/include/python2.7/abstract.h:501:22: error:   initializing argument 3 of ‘int PyObject_AsReadBuffer(PyObject*, const void**, Py_ssize_t*)’ [-fpermissive]
      PyAPI_FUNC(int) PyObject_AsReadBuffer(PyObject *obj,
                      ^
make[2]: *** [meshpy/CMakeFiles/meshrender.dir/meshrender.cpp.o] Fehler 1
make[2]: Verzeichnis »/dex-net/deps/meshpy/build« wird verlassen
make[1]: *** [meshpy/CMakeFiles/meshrender.dir/all] Fehler 2
make[1]: Verzeichnis »/dex-net/deps/meshpy/build« wird verlassen
make: *** [all] Fehler 2
