### ISSUE TITLE
python (no ROS) test failed

### ISSUE THREAD

**Issue by EvanLavizadeh** [BerkeleyAutomation/dex-net#37]
After hunting for broken dependencies, the installation is successful but the test is unsuccessful. Here are the results. It's hard to sift through with all the warnings but there are errors in several places. Let me know what info you need and anything I can do to help. 

`sudo python setup.py test`

```
running test
Searching for dill
Reading https://pypi.org/simple/dill/
Downloading https://files.pythonhosted.org/packages/fe/42/bfe2e0857bc284cbe6a011d93f2a9ad58a22cb894461b199ae72cfef0f29/dill-0.2.9.tar.gz#sha256=f6d6046f9f9195206063dd0415dff185ad593d6ee8b0e67f12597c0f4df4986f
Best match: dill 0.2.9
Processing dill-0.2.9.tar.gz
Writing /tmp/easy_install-Rq9WAV/dill-0.2.9/setup.cfg
Running dill-0.2.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Rq9WAV/dill-0.2.9/egg-dist-tmp-NIXNL8
creating /home/evan/dex-net-python/dex-net/.eggs/dill-0.2.9-py2.7.egg
Extracting dill-0.2.9-py2.7.egg to /home/evan/dex-net-python/dex-net/.eggs

Installed /home/evan/dex-net-python/dex-net/.eggs/dill-0.2.9-py2.7.egg
running egg_info
error: [Errno 13] Permission denied: 'src/dex_net.egg-info'
evan@evan:~/dex-net-python/dex-net$ sudo python setup.py test
[sudo] password for evan: 
running test
running egg_info
writing requirements to src/dex_net.egg-info/requires.txt
writing src/dex_net.egg-info/PKG-INFO
writing top-level names to src/dex_net.egg-info/top_level.txt
writing dependency_links to src/dex_net.egg-info/dependency_links.txt
reading manifest file 'src/dex_net.egg-info/SOURCES.txt'
writing manifest file 'src/dex_net.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
Unable to import meshrender shared library! Rendering will not work. Likely due to missing Boost.Numpy
Boost.Numpy can be installed following the instructions in https://github.com/ndarray/Boost.NumPy
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:autolab_perception is not installed as a catkin package - ROS msg conversions will not be available for image wrappers
WARNING:root:Unable to import CNN modules! Likely due to missing tensorflow.
WARNING:root:TensorFlow can be installed following the instructions in https://www.tensorflow.org/get_started/os_setup
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Failed to import ROS in Kinect2_sensor.py. Kinect will not be able to be used in bridged mode
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Failed to import ROS in primesense_sensor.py. ROS functionality not available
WARNING:root:primesense_sensor.py not installed as catkin package. ROS functionality not available.
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in realsense_sensor.py. ROS functionality not available
WARNING:root:realsense_sensor.py not installed as catkin package. ROS functionality not available.
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:root:Unable to import weight sensor modules!
WARNING:root:Failed to import gqcnn! Grasp2D functions will not be available.
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import pyhull
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:root:Failed to import mayavi
WARNING:dexnet.api:Failed to import DexNetVisualizer3D, visualization methods will be unavailable
test_gaussian_uniform_alloc (test.learning_test.LearningTest) ... ok
test_thompson_sampling (test.learning_test.LearningTest) ... ok
test_uniform_alloc (test.learning_test.LearningTest) ... ok
test_antipodal_grasp_sampler (test.grasping_test.GraspTest) ... ERROR:root:Singular matrix. Probably a bug
ok
test_contacts (test.grasping_test.GraspTest) ... ok
test_find_contacts (test.grasping_test.GraspTest) ... ok
test_force_closure (test.grasping_test.GraspTest) ... ok
test_grasp_quality_functions (test.grasping_test.GraspTest) ... ok
test_init_grasp (test.grasping_test.GraspTest) ... ok
test_init_graspable (test.grasping_test.GraspTest) ... ok
test_init_gripper (test.grasping_test.GraspTest) ... ok
test_min_norm_vector_in_facet (test.grasping_test.GraspTest) ... ok
test_wrench_in_positive_span (test.grasping_test.GraspTest) ... ok
test_illegal_create (test.database_test.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest) ... Input mesh  /home/evan/dex-net-python/dex-net/data/test/models/bar_clamp.obj
output mesh  /home/evan/dex-net-python/dex-net/.dexnet/bar_clamp_proc.obj
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh bar_clamp.obj loaded has 1428 vn 476 fn
No Script to apply.
Mesh /home/evan/dex-net-python/dex-net/data/test/models/bar_clamp.obj saved as /home/evan/dex-net-python/dex-net/.dexnet/bar_clamp_proc.obj (1428 vn 476 fn)
Reading data.
Warning: 9 lines were ignored since they did not contain faces or vertices.
Read in 1428 vertices and 476 faces.
Resolution: 0.000716689 with real dimension 0.064502
Center of grid 0 0 0
Bound box size: (-0.0358344 -0.0358344 -0.0358344) to (0.021729 0.02 0.032251) with dimensions 100 100 100.
Computing signed distance field.
Writing results to: .dexnet/bar_clamp_proc.sdf
Processing complete.
ERROR

======================================================================
ERROR: test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/evan/dex-net-python/dex-net/test/database_test.py", line 168, in test_new_database_and_graspable
    stable_pose)
  File "/home/evan/dex-net-python/dex-net/deps/meshpy/meshpy/mesh_renderer.py", line 716, in wrapped_images_viewsphere
    return self.wrapped_images(mesh, vs_disc.object_to_camera_poses(), render_mode, stable_pose=stable_pose, mat_props=mat_props, light_props=light_props)
  File "/home/evan/dex-net-python/dex-net/deps/meshpy/meshpy/mesh_renderer.py", line 587, in wrapped_images
    debug=debug)
  File "/home/evan/dex-net-python/dex-net/deps/meshpy/meshpy/mesh_renderer.py", line 489, in images
    c, d = meshrender.render_mesh([P],
NameError: global name 'meshrender' is not defined

----------------------------------------------------------------------
Ran 15 tests in 96.862s

FAILED (errors=1)
Floating point exception (core dumped)

```

**Comment by EvanLavizadeh** [comment]
Duplicate issue, my bad.
