### ISSUE TITLE
KeyError: "Can't open attribute (Can't locate attribute: 'num_stable_poses')"

### ISSUE THREAD

**Issue by amritkochar** [BerkeleyAutomation/dex-net#40]
I added 3 new objects using the CLI to the existing example.hdf5 database and it was smooth. But when I executed generate_gqcnn_dataset.py I found out that 0 stable poses were generated for these 3 objects. I cannot understand the reason for the same.

Please help me out with this, thank you!

Here is the entire error message from the terminal. 

> Traceback (most recent call last):
>   File "tools/generate_gqcnn_dataset.py", line 579, in <module>
>     config)
>   File "tools/generate_gqcnn_dataset.py", line 343, in generate_gqcnn_dataset
>     stable_poses = dataset.stable_poses(obj.key)
>   File "/home/loccioni/DexNet/src/dexnet/database/database.py", line 1072, in stable_poses
>     stps = Hdf5ObjectFactory.stable_poses(self.stable_pose_data(key))
>   File "/home/loccioni/DexNet/src/dexnet/database/hdf5_factory.py", line 66, in stable_poses
>     num_stable_poses = data.attrs[NUM_STP_KEY]
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
>   File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/attrs.py", line 58, in __getitem__
>     attr = h5a.open(self._id, self._e(name))
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
>   File "h5py/h5a.pyx", line 77, in h5py.h5a.open (/tmp/pip-4rPeHA-build/h5py/h5a.c:2172)

Thank you.

**Comment by jeffmahler** [comment]
@amrit-007 What are the objects? Spherical objects could cause this, or there may be a problem with the meshes.

**Comment by amritkochar** [comment]
Hello @jeffmahler, they are not spherical. I am attaching the .OBJ files with this comment for your perusal.


[Objects.zip](https://github.com/BerkeleyAutomation/dex-net/files/3222583/Objects.zip)

**Comment by amritkochar** [comment]
Hello team,

Could you please help me with this error, because I have tried every thing from my end. 

When, I use Dexnet as a service on http://automation.berkeley.edu/dex-net/#, with these objects there are grasps which get generated. Is there any way I can download the .json from here and add them to the database. 

Please help!

**Comment by jeffmahler** [comment]
@amrit-007 Apologies for the delay. Your OBJ files look good to me.

@Binaryhalibut Is there a tool for importing grasps from DNaaS into a Dex-Net database?

**Comment by 01halibut** [comment]
No, there isn't a tool for importing DNaaS grasps into a Dex-Net database
at the moment.

**Comment by amritkochar** [comment]
Hi @Binaryhalibut, 

Is there any way (any workaround) to add my objects to an existing .hdf5 database if adding it via dexnet_cli.py is not generating any stable poses but DNaaS does compute stable poses?

**Comment by mariabauza** [comment]
Hi @amrit-007 ,
We had the same problem and the solution was to save the stl files in meters. Originally they where in millimeters and no stable poses were found unless the min_prob was set really low.

Hope it helps!

**Comment by elevenjiang1** [comment]
I also have this problem by self make database. Even the object are from their shapes.
Hoping to provide the origin parameters of generate database and generate gqcnn @jeffmahler 

Best
