### ISSUE TITLE
ValueError: SDF computation failed for .dexnet/bar_clamp_proc.sdf

### ISSUE THREAD

**Issue by imdoublecats** [BerkeleyAutomation/dex-net#53]
I installed dex-net with gpu python on Ubuntu 16.04 LTS. When I ran "python setup.py test", an error occured. Here is the log:

running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing requirements to src/dex_net.egg-info/requires.txt
writing src/dex_net.egg-info/PKG-INFO
writing top-level names to src/dex_net.egg-info/top_level.txt
writing dependency_links to src/dex_net.egg-info/dependency_links.txt
reading manifest file 'src/dex_net.egg-info/SOURCES.txt'
writing manifest file 'src/dex_net.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Failed to import ROS in Kinect2_sensor.py. Kinect will not be able to be used in bridged mode
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:root:Unable to import weight sensor modules!
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/siasun/workspace/wyl/dex-net-master/deps/gqcnn/gqcnn/utils/enums.py:44: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

root       WARNING  Failed to import gqcnn! Grasp2D functions will not be available.
Qt: Session management error: None of the authentication protocols specified are supported
root       WARNING  Failed to import OpenRAVE
root       WARNING  Failed to import OpenRAVE
test_illegal_create (test.database_test.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest) ... Input mesh  /home/siasun/workspace/wyl/dex-net-master/data/test/models/bar_clamp.obj
output mesh  /home/siasun/workspace/wyl/dex-net-master/.dexnet/bar_clamp_proc.obj
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh bar_clamp.obj loaded has 1428 vn 476 fn
No Script to apply.
Mesh /home/siasun/workspace/wyl/dex-net-master/data/test/models/bar_clamp.obj saved as /home/siasun/workspace/wyl/dex-net-master/.dexnet/bar_clamp_proc.obj (1428 vn 476 fn)
root       INFO     MeshlabServer Command: meshlabserver -i "data/test/models/bar_clamp.obj" -o ".dexnet/bar_clamp_proc.obj"
sh: 1: SDFGen: not found
root       INFO     SDF Command: SDFGen ".dexnet/bar_clamp_proc.obj" 100 5
ERROR
test_gaussian_uniform_alloc (test.learning_test.LearningTest) ... ok
test_thompson_sampling (test.learning_test.LearningTest) ... ok
test_uniform_alloc (test.learning_test.LearningTest) ... ok
test_antipodal_grasp_sampler (test.grasping_test.GraspTest) ... root       INFO     Num surface: 30160
root       INFO     17/100 grasps found after iteration 1.
root       INFO     Num surface: 30160
root       ERROR    Singular matrix. Probably a bug
root       INFO     37/100 grasps found after iteration 2.
root       INFO     Num surface: 30160
root       INFO     57/100 grasps found after iteration 3.
root       INFO     Found 57 grasps.
ok
test_contacts (test.grasping_test.GraspTest) ... root       INFO     25/100 grasps found after iteration 1.
root       INFO     56/100 grasps found after iteration 2.
root       INFO     78/100 grasps found after iteration 3.
root       INFO     Found 78 grasps.
ok
test_find_contacts (test.grasping_test.GraspTest) ... ok
test_force_closure (test.grasping_test.GraspTest) ... ok
test_grasp_quality_functions (test.grasping_test.GraspTest) ... root       INFO     26/100 grasps found after iteration 1.
root       INFO     51/100 grasps found after iteration 2.
root       INFO     76/100 grasps found after iteration 3.
root       INFO     Found 76 grasps.
ok
test_init_grasp (test.grasping_test.GraspTest) ... ok
test_init_graspable (test.grasping_test.GraspTest) ... ok
test_init_gripper (test.grasping_test.GraspTest) ... ok
test_min_norm_vector_in_facet (test.grasping_test.GraspTest) ... ok
test_wrench_in_positive_span (test.grasping_test.GraspTest) ... ok

======================================================================
ERROR: test_new_database_and_graspable (test.database_test.Hdf5DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/siasun/workspace/wyl/dex-net-master/test/database_test.py", line 91, in test_new_database_and_graspable
    mesh_processor.generate_graspable(CONFIG)
  File "/home/siasun/workspace/wyl/dex-net-master/src/dexnet/database/mesh_processor.py", line 160, in generate_graspable
    self._generate_sdf(config['path_to_sdfgen'], config['sdf_dim'], config['sdf_padding'])
  File "/home/siasun/workspace/wyl/dex-net-master/src/dexnet/database/mesh_processor.py", line 334, in _generate_sdf
    raise ValueError('SDF computation failed for %s' %(self.sdf_filename))
ValueError: SDF computation failed for .dexnet/bar_clamp_proc.sdf

----------------------------------------------------------------------
Ran 15 tests in 104.199s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>

**Comment by imdoublecats** [comment]
1.SDFGen was not installed properly，i reinstalled it by running the command under the directory"deps/SDFGen":
`sh install.sh`
2.Because I'm using an anaconda environment instead of the system environment, the path of SDFGen should be added to the environment.
run the following command in the anaconda environment:
`export PATH=<the path of SDFGen executable file>:$PATH`
