### ISSUE TITLE
'module' object has no attribute 'solvers' after running 'sudo python setup.py test'

### ISSUE THREAD

**Issue by Todibo99** [BerkeleyAutomation/dex-net#60]
Hi, 
When I run 'sudo python setup.py test', I get this:

`running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing requirements to src/dex_net.egg-info/requires.txt
writing src/dex_net.egg-info/PKG-INFO
writing top-level names to src/dex_net.egg-info/top_level.txt
writing dependency_links to src/dex_net.egg-info/dependency_links.txt
reading manifest file 'src/dex_net.egg-info/SOURCES.txt'
writing manifest file 'src/dex_net.egg-info/SOURCES.txt'
running build_ext
WARNING:root:Failed to import geometry msgs in rigid_transformations.py.
WARNING:root:Failed to import ros dependencies in rigid_transforms.py
WARNING:root:autolab_core not installed as catkin package, RigidTransform ros methods will be unavailable
WARNING:root:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:Failed to import ROS in Kinect2_sensor.py. Kinect will not be able to be used in bridged mode
WARNING:root:Unable to import openni2 driver. Python-only Primesense driver may not work properly
WARNING:root:Unable to import pyrealsense2.
WARNING:root:Failed to import ROS in ensenso_sensor.py. ROS functionality not available
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:root:Unable to import weight sensor modules!
WARNING:tensorflow:From /home/jl/dex-net/deps/gqcnn/gqcnn/utils/enums.py:40: The name tf.RunOptions is deprecated. Please use tf.compat.v1.RunOptions instead.

root       WARNING  Failed to import gqcnn! Grasp2D functions will not be available.
root       WARNING  Failed to import mayavi
root       WARNING  Failed to import mayavi
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    test_suite='test'
  File "/home/jl/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/jl/.local/lib/python2.7/site-packages/setuptools/command/test.py", line 237, in run
    self.run_tests()
  File "/home/jl/.local/lib/python2.7/site-packages/setuptools/command/test.py", line 259, in run_tests
    exit=False,
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/jl/.local/lib/python2.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/jl/dex-net/test/learning_test.py", line 38, in <module>
    from dexnet.learning import RandomBinaryObjective, RandomContinuousObjective, UniformAllocationMean, ThompsonSampling, GaussianUniformAllocationMean, MaxIterTerminationCondition
  File "/home/jl/dex-net/src/dexnet/__init__.py", line 24, in <module>
    from api import DexNet
  File "/home/jl/dex-net/src/dexnet/api.py", line 42, in <module>
    import dexnet.database.database as db
  File "/home/jl/dex-net/src/dexnet/database/__init__.py", line 22, in <module>
    from hdf5_factory import Hdf5ObjectFactory
  File "/home/jl/dex-net/src/dexnet/database/hdf5_factory.py", line 41, in <module>
    from dexnet.grasping import ParallelJawPtGrasp3D
  File "/home/jl/dex-net/src/dexnet/grasping/__init__.py", line 27, in <module>
    from quality import PointGraspMetrics3D
  File "/home/jl/dex-net/src/dexnet/grasping/quality.py", line 55, in <module>
    cvx.solvers.options['show_progress'] = False
AttributeError: 'module' object has no attribute 'solvers'
`

Does anyone know the solution of this problem?
Thanks!

**Comment by JJayaL** [comment]
Could you please explain how you solved this issue?
